#!/bin/sh

. scenario.conf

scenariodir=$workdir/scenario
[ -d $scenariodir ] && rm -rf $scenariodir
mkdir -p $scenariodir

for topology in $topologies ; do

scenario2dir=$scenariodir/$topology
[ -d $scenario2dir ] && rm -rf $scenario2dir
mkdir -p $scenario2dir

  for seed in $seeds ; do

echo $scenario2dir/traffic1-$topology-seed${seed}.scenario

cat > $scenario2dir/traffic1-$topology-seed${seed}.scenario << EOL
graph 100
 import brite $topodir/$topology.brite
exit
show graph 100 structure

weight 100
 weight-graph 100
 weight-setting inverse-capacity
exit
show weight 100

routing 100
 routing-graph 100
 routing-weight 100
 routing-algorithm dijkstra
exit
show routing 100

routing 200
 routing-graph 100
 routing-algorithm lbra
exit
show routing 200

traffic 100
 traffic-graph 100
 traffic-seed ${seed}
 traffic-set random random bandwidth ${bandwidth}
exit
show traffic 100

network 100
 network-graph 100
 network-traffic 100
 network-routing 100
 network-load traffic-flows
exit
show network 100

network 200
 network-graph 100
 network-traffic 100
 network-routing 200
 network-load traffic-flows
exit
show network 200

EOL

  done
done


